### ISSUE TITLE
EMA not calculating?

### ISSUE THREAD

**Issue by Phnmz** [buzzpranav/binance-tradingbot.py#1]
Hi, i tested your script and EMA is not calculating at all can you please fix it? Thanks!

**Comment by RandomPerson06** [comment]
Thanks for testing! There are 2 possible problems. 
1. You haven't created a config.py file and created variables for the API (I gave a small explanation of how to do that in the readme)
2. You need to add the previous EMA's on line 26 and 27  like this:
![image](https://user-images.githubusercontent.com/84334708/120109317-866cfc80-c186-11eb-9a99-ca7132fb4104.png)

Also, I'll be making converting this into a command line app so that you wouldn't have to do all of this manually :)

**Comment by Phnmz** [comment]
> Thanks for testing! There are 2 possible problems.
> 
> 1. You haven't created a config.py file and created variables for the API (I gave a small explanation of how to do that in the readme)
> 2. You need to add the previous EMA's on line 26 and 27  like this:
>    ![image](https://user-images.githubusercontent.com/84334708/120109317-866cfc80-c186-11eb-9a99-ca7132fb4104.png)
> 
> Also, I'll be making converting this into a command line app so that you wouldn't have to do all of this manually :)

ohhhh i have to add this manually each time okay then thanks!! :)

**Comment by Phnmz** [comment]
Can you please send me your Discord username so i can send you messages? There is some stuff i have to ask you about, it would really help me.. Thanks!

**Comment by RandomPerson06** [comment]
My Discord username is Error404#1498
:)

**Comment by Phnmz** [comment]
Alright, added you! ^^
